import { AuthenticationService } from 'src/authentication/authentication.service';
import { ConfigService } from 'src/config/config.service';
import { ErrorCodes } from 'src/constants/error-codes';
import { Injectable, UnauthorizedException } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import {
  QnapAuthLoginDto,
  QnapAuthLoginQueryDto,
  QnapAuthResumeSessionDto,
  QnapPreauthenticateDto,
} from './dtos/auth-login.dto';
import { SessionRestrictionEnum } from 'src/types/enums';

@Injectable()
export class QnapAuthLoginService {
  constructor(
    private readonly authenticationService: AuthenticationService,
    private readonly configService: ConfigService,
    private readonly jwtService: JwtService,
  ) {}

  preauthenticate(): QnapPreauthenticateDto {
    return {
      doQuick: '',
      is_booting: 0,
      mediaReady: 1,
      shutdown_info: {
        type: -1,
        timestamp: 0,
        duration: 0,
      },
      hostname: 'music-server',
      DemoSiteSuppurt: 'no',
      webAccessPort: 80,
      stunnelEnabled: 1,
      stunnelPort: 443,
      support_ksmbd: 'yes',
      passwdConstraints: {
        passwdConstraint01: 0,
        passwdConstraint02: 0,
        passwdConstraint03: 0,
        passwdConstraint04: 0,
        pw_constraint01_opt: 3,
        pw_constraint01_letter: 0,
        pw_min_limit_en: 1,
        pw_min_limit: 8,
      },
      ts: 92782397,
      fwNotice: 0,
      title: '',
      content: '',
      psType: 1,
      standard_massage: '',
      standard_color: '#ffffff',
      standard_size: '12px',
      standard_bg_style: 'fill',
      showVersion: 0,
      show_link: 1,
      cuid: this.configService.get('QNAP_CUID') || '',
      auth_method: 'ck',
      mfa_support: '',
      function_support: 'redirect_url,xs-auth-redirect,passwordless_login,multi_2sv,app_privilege',
    };
  }

  async authenticate(userAgent: string, query: QnapAuthLoginQueryDto): Promise<QnapAuthLoginDto> {
    const username = query.user;
    const password = query.pwd;
    const jwtToken = await this.authenticationService.createSession(
      username,
      password,
      userAgent,
      SessionRestrictionEnum.QNAP_MUSICSTATION,
      3650,
    );
    return {
      doQuick: '',
      is_booting: 0,
      mediaReady: 1,
      shutdown_info: {
        type: -1,
        timestamp: 0,
        duration: 0,
      },
      pw_status: 0,
      qtoken: jwtToken,
      authPassed: 1,
      SMBFW: 0,
      hero_model: 1,
      qts_mode_type: 0,
      user_enable: 1,
      user_account_expiry: 0,
      authSid: jwtToken,
      isAdmin: 1,
      username,
      groupname: 'everyone',
      model: {
        modelName: 'TS-KVM-CLD',
        internalModelName: 'TS-KVM',
        platform: 'TS-NASX86',
        platform_ex: 'X86_KVM',
        customModelName: '',
        displayModelName: 'Music Server',
        sas_model: 0,
        storage_v2: 1,
        encryptfsSupported: 1,
        is_zfs: 0,
        vqts: 'cloud_host',
        node: '',
        dual_node: '',
      },
      firmware: {
        name: 'QuTScloud',
        version: 'c5.2.9',
        number: 3468,
        build: 20260413,
        patch: 0,
        buildTime: '2026/04/13',
      },
      rfs_bits: 64,
      specVersion: '1.0',
      hostname: 'music-server',
      DemoSiteSuppurt: 'no',
      customLogo: {
        customFrontLogo: '',
        customLoginLogo: '',
      },
      webAccessPort: this.configService.get('LAN_SERVER_PORT') || this.configService.get('SERVER_PORT'),
      HTTPHost: this.configService.get('LAN_SERVER_ADDRESS') || this.configService.get('SERVER_ADDRESS'),
      QWebPort: 80,
      webFSEnabled: 1,
      QMultimediaEnabled: 0,
      MSV2Supported: 0,
      MSV2WebEnabled: 1,
      MSV2URL: '/MSV2/',
      QDownloadEnabled: 0,
      DSV2Supported: 0,
      DSV3Supported: 1,
      DSV2URL: '/downloadstation/?ssid=',
      QWebEnabled: 0,
      QWebSSLEnabled: 1,
      QWebSSLPort: 8081,
      NVREnabled: 0,
      NVRURL: '/surveillance/',
      NVRVER: 1,
      WFM2: 1,
      wfmPortEnabled: 0,
      wfmPort: 8080,
      wfmSSLEnabled: 0,
      wfmSSLPort: 443,
      wfmURL: '/filestation/',
      QMusicsEnabled: 1,
      QMusicsURL: '/musicstation/',
      QVideosEnabled: 0,
      QVideosURL: '/videostation/',
      QPhotosEnabled: 0,
      QPhotosURL: '/photostation/',
      HDAROOT_ALMOST_FULL: 0,
      forceSSL: 0,
      stunnelEnabled: 1,
      stunnelPort: 443,
      support_ksmbd: 'yes',
      passwdConstraints: {
        passwdConstraint01: 0,
        passwdConstraint02: 0,
        passwdConstraint03: 0,
        passwdConstraint04: 0,
        pw_constraint01_opt: 3,
        pw_constraint01_letter: 0,
        pw_min_limit_en: 1,
        pw_min_limit: 8,
      },
      serviceURL: '/filestation/',
      ts: 92782397,
      fwNotice: 0,
      SUID: jwtToken,
      title: '',
      content: '',
      psType: 1,
      standard_massage: '',
      standard_color: '#ffffff',
      standard_size: '12px',
      standard_bg_style: 'fill',
      showVersion: 0,
      show_link: 1,
      cuid: this.configService.get('QNAP_CUID') || '',
      auth_method: 'ck',
      mfa_support: '',
      function_support: 'redirect_url,xs-auth-redirect,passwordless_login,multi_2sv,app_privilege',
    };
  }

  async resumeSession(jwtToken: string, ipAddress: string): Promise<QnapAuthResumeSessionDto> {
    return {
      doQuick: '',
      is_booting: 0,
      mediaReady: 1,
      shutdown_info: {
        type: -1,
        timestamp: 0,
        duration: 0,
      },
      authPassed: 1,
      SMBFW: 0,
      hero_model: 1,
      qts_mode_type: 0,
      isAdmin: 1,
      user: 'qnap',
      username: 'qnap',
      groupname: 'everyone',
      userid: 1000,
      force_2sv: 0,
      userType: 'local',
      model: {
        modelName: 'TS-KVM-CLD',
        internalModelName: 'TS-KVM',
        platform: 'TS-NASX86',
        platform_ex: 'X86_KVM',
        customModelName: '',
        displayModelName: 'QuTScloud',
        sas_model: 0,
        storage_v2: 1,
        encryptfsSupported: 1,
        is_zfs: 0,
        vqts: 'cloud_host',
        node: '',
        dual_node: '',
      },
      firmware: {
        name: 'QuTScloud',
        version: 'c5.2.9',
        number: 3468,
        build: 20260413,
        patch: 0,
        buildTime: '2026/04/13',
      },
      rfs_bits: 64,
      specVersion: '1.0',
      hostname: 'QNAP-Demo',
      DemoSiteSuppurt: 'no',
      customLogo: {
        customFrontLogo: '',
        customLoginLogo: '',
      },
      gqMaster: -1,
      webAccessPort: this.configService.get('LAN_SERVER_PORT') || this.configService.get('SERVER_PORT'),
      HTTPHost: this.configService.get('LAN_SERVER_ADDRESS') || this.configService.get('SERVER_ADDRESS'),
      QWebPort: 80,
      webFSEnabled: 1,
      QMultimediaEnabled: 0,
      MSV2Supported: 0,
      MSV2WebEnabled: 1,
      MSV2URL: '/MSV2/',
      QDownloadEnabled: 0,
      DSV2Supported: 0,
      DSV3Supported: 1,
      DSV2URL: '/downloadstation/?ssid=',
      QWebEnabled: 0,
      QWebSSLEnabled: 1,
      QWebSSLPort: 8081,
      NVREnabled: 0,
      NVRURL: '/surveillance/',
      NVRVER: 1,
      WFM2: 1,
      wfmPortEnabled: 0,
      wfmPort: 8080,
      wfmSSLEnabled: 0,
      wfmSSLPort: 443,
      wfmURL: '/filestation/',
      QMusicsEnabled: 1,
      QMusicsURL: '/musicstation/',
      QVideosEnabled: 0,
      QVideosURL: '/videostation/',
      QPhotosEnabled: 0,
      QPhotosURL: '/photostation/',
      HDAROOT_ALMOST_FULL: 0,
      forceSSL: 0,
      stunnelEnabled: 1,
      stunnelPort: 443,
      support_ksmbd: 'yes',
      passwdConstraints: {
        passwdConstraint01: 0,
        passwdConstraint02: 0,
        passwdConstraint03: 0,
        passwdConstraint04: 0,
        pw_constraint01_opt: 3,
        pw_constraint01_letter: 0,
        pw_min_limit_en: 1,
        pw_min_limit: 8,
      },
      quickStart: 1,
      connet_info: {
        connet_ip: ipAddress,
      },
      ts: 92911688,
      fwNotice: 0,
      SUID: jwtToken,
      title: '',
      content: '',
      psType: 1,
      standard_massage: '',
      standard_color: '#ffffff',
      standard_size: '12px',
      standard_bg_style: 'fill',
      showVersion: 0,
      show_link: 1,
      cuid: this.configService.get('QNAP_CUID') || '',
      auth_method: 'ck',
      mfa_support: '',
      function_support: 'redirect_url,xs-auth-redirect,passwordless_login,multi_2sv,app_privilege',
      _version: '1.0',
    };
  }

  async validateExistingSession(jwtToken: string): Promise<QnapAuthLoginDto> {
    const payload: {
      accountId: number;
      sessionId: number;
      tokenHash: string;
    } = await this.jwtService.verifyAsync(jwtToken);
    const user = await this.authenticationService.getAccount(payload.accountId);
    if (!user) {
      throw new UnauthorizedException(ErrorCodes.AUTHORIZATION_ERROR, 'session-error-1');
    }
    const session = await this.authenticationService.getSession(payload.sessionId);
    if (!session || session.expiresAt.getTime() < new Date().getTime() || session.endedAt !== null) {
      throw new UnauthorizedException(ErrorCodes.AUTHORIZATION_ERROR, 'session-error-2');
    }
    const validSessionToken = await this.authenticationService.verifySessionToken(user, session, payload.tokenHash);
    if (!validSessionToken) {
      throw new UnauthorizedException(ErrorCodes.AUTHORIZATION_ERROR, 'session-error-3');
    }
    return {
      doQuick: '',
      is_booting: 0,
      mediaReady: 1,
      shutdown_info: {
        type: -1,
        timestamp: 0,
        duration: 0,
      },
      pw_status: 0,
      qtoken: jwtToken,
      authPassed: 1,
      SMBFW: 0,
      hero_model: 1,
      qts_mode_type: 0,
      user_enable: 1,
      user_account_expiry: 0,
      authSid: jwtToken,
      isAdmin: 1,
      username: user.username,
      groupname: 'everyone',
      model: {
        modelName: 'TS-KVM-CLD',
        internalModelName: 'TS-KVM',
        platform: 'TS-NASX86',
        platform_ex: 'X86_KVM',
        customModelName: '',
        displayModelName: 'Music Server',
        sas_model: 0,
        storage_v2: 1,
        encryptfsSupported: 1,
        is_zfs: 0,
        vqts: 'cloud_host',
        node: '',
        dual_node: '',
      },
      firmware: {
        name: 'QuTScloud',
        version: 'c5.2.9',
        number: 3468,
        build: 20260413,
        patch: 0,
        buildTime: '2026/04/13',
      },
      rfs_bits: 64,
      specVersion: '1.0',
      hostname: 'music-server',
      DemoSiteSuppurt: 'no',
      customLogo: {
        customFrontLogo: '',
        customLoginLogo: '',
      },
      webAccessPort:
        this.configService.get('WAN_SERVER_PORT') ||
        this.configService.get('LAN_SERVER_PORT') ||
        this.configService.get('SERVER_PORT'),
      HTTPHost:
        this.configService.get('WAN_SERVER_ADDRESS') ||
        this.configService.get('LAN_SERVER_ADDRESS') ||
        this.configService.get('SERVER_ADDRESS'),
      QWebPort: 80,
      webFSEnabled: 1,
      QMultimediaEnabled: 0,
      MSV2Supported: 0,
      MSV2WebEnabled: 1,
      MSV2URL: '/MSV2/',
      QDownloadEnabled: 0,
      DSV2Supported: 0,
      DSV3Supported: 1,
      DSV2URL: '/downloadstation/?ssid=',
      QWebEnabled: 0,
      QWebSSLEnabled: 1,
      QWebSSLPort: 8081,
      NVREnabled: 0,
      NVRURL: '/surveillance/',
      NVRVER: 1,
      WFM2: 1,
      wfmPortEnabled: 0,
      wfmPort: 8080,
      wfmSSLEnabled: 0,
      wfmSSLPort: 443,
      wfmURL: '/filestation/',
      QMusicsEnabled: 1,
      QMusicsURL: '/musicstation/',
      QVideosEnabled: 0,
      QVideosURL: '/videostation/',
      QPhotosEnabled: 0,
      QPhotosURL: '/photostation/',
      HDAROOT_ALMOST_FULL: 0,
      forceSSL: 0,
      stunnelEnabled: 1,
      stunnelPort: 443,
      support_ksmbd: 'yes',
      passwdConstraints: {
        passwdConstraint01: 0,
        passwdConstraint02: 0,
        passwdConstraint03: 0,
        passwdConstraint04: 0,
        pw_constraint01_opt: 3,
        pw_constraint01_letter: 0,
        pw_min_limit_en: 1,
        pw_min_limit: 8,
      },
      serviceURL: '/filestation/',
      ts: 92782397,
      fwNotice: 0,
      SUID: jwtToken,
      title: '',
      content: '',
      psType: 1,
      standard_massage: '',
      standard_color: '#ffffff',
      standard_size: '12px',
      standard_bg_style: 'fill',
      showVersion: 0,
      show_link: 1,
      cuid: this.configService.get('QNAP_CUID') || '',
      auth_method: 'ck',
      mfa_support: '',
      function_support: 'redirect_url,xs-auth-redirect,passwordless_login,multi_2sv,app_privilege',
    };
  }
}
